name: "🐛 Task"
description: Use this for team work
title: "[Task]: "
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: Describe the issue to work with

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: A concise description of what the problem is.
      placeholder: "e.g. We want to …"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the proposal solution"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the tasks need to work with the issue"
      description: Tasks list
  - type: textarea
    attributes:
      label: "Documentation, Adoption, Migration Strategy"
      description: |
        If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?